person_index:
    path:     /
    defaults: { _controller: "CompaniesBundle:person:index" }
    methods:  GET

person_show:
    path:     /{id}/show
    defaults: { _controller: "CompaniesBundle:person:show" }
    methods:  GET

person_new:
    path:     /new
    defaults: { _controller: "CompaniesBundle:person:new" }
    methods:  [GET, POST]

person_edit:
    path:     /{id}/edit
    defaults: { _controller: "CompaniesBundle:person:edit" }
    methods:  [GET, POST]

person_delete:
    path:     /{id}/delete
    defaults: { _controller: "CompaniesBundle:person:delete" }
    methods:  DELETE
