<?php

namespace CompaniesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * companyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class companyRepository extends EntityRepository
{
}
