<?php

namespace CompaniesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * officeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class officeRepository extends EntityRepository
{
}
